In [41]:
import pandas as pd
import requests
import os
import datetime
import time
import json

In [42]:
from pycoingecko import CoinGeckoAPI
cg = CoinGeckoAPI()

In [43]:
# Create unix from date
start_date = pd.Timestamp('2021-09-01').timestamp()
start_date

1630454400.0

In [44]:
# Create unix end date
end_date = pd.Timestamp('2021-09-30').timestamp()
end_date

1632960000.0

In [45]:
# pull bitcoin data for sep 2021
sep_2021_btc = cg.get_coin_market_chart_range_by_id(id='bitcoin', vs_currency='usd', from_timestamp=start_date, to_timestamp=end_date)
sep_2021_btc_prices = sep_2021_btc['prices']
sep_2021_btc_prices = pd.DataFrame(sep_2021_btc_prices)
sep_2021_btc_prices.head()

               0             1
0  1630454466008  47335.420299
1  1630458081410  46857.500212
2  1630461714396  46955.623803
3  1630465275595  46961.450121
4  1630468943822  47039.724708

In [46]:
# create just the price data for btc
sep_2021_btc_prices.columns = ['date(unix)', 'price']
sep_2021_btc_prices

        date(unix)         price
0    1630454466008  47335.420299
1    1630458081410  46857.500212
2    1630461714396  46955.623803
3    1630465275595  46961.450121
4    1630468943822  47039.724708
..             ...           ...
691  1632942389915  41353.694888
692  1632945895453  41313.872059
693  1632949623225  41252.229439
694  1632953361935  41352.682410
695  1632956449081  41537.908786

[696 rows x 2 columns]

In [47]:
# teset a to datetime
pd.to_datetime('1632953361935', unit='ms')

Timestamp('2021-09-29 22:09:21.935000')

In [48]:
# Convert unix date to normal date
sep_2021_btc_prices['date(unix)'] = pd.to_datetime(sep_2021_btc_prices['date(unix)'], unit='ms')
sep_2021_btc_prices.head()

               date(unix)         price
0 2021-09-01 00:01:06.008  47335.420299
1 2021-09-01 01:01:21.410  46857.500212
2 2021-09-01 02:01:54.396  46955.623803
3 2021-09-01 03:01:15.595  46961.450121
4 2021-09-01 04:02:23.822  47039.724708

In [49]:
# Convert to isoformat
sep_2021_btc_prices['date(unix)'] = pd.Timestamp(sep_2021_btc_prices['date(unix)'], tz="America/New_York").isoformat()
sep_2021_btc_prices

TypeError: Cannot convert input [0     2021-09-01 00:01:06.008
1     2021-09-01 01:01:21.410
2     2021-09-01 02:01:54.396
3     2021-09-01 03:01:15.595
4     2021-09-01 04:02:23.822
                ...
691   2021-09-29 19:06:29.915
692   2021-09-29 20:04:55.453
693   2021-09-29 21:07:03.225
694   2021-09-29 22:09:21.935
695   2021-09-29 23:00:49.081
Name: date(unix), Length: 696, dtype: datetime64[ns]] of type <class 'pandas.core.series.Series'> to Timestamp

In [28]:
# find average
sep_2021_btc_prices = sep_2021_btc_prices.pct_change().dropna()
sep_2021_btc_prices.head()

1   -0.010096
2    0.002094
3    0.000124
4    0.001667
5    0.002774
Name: price, dtype: float64

In [62]:
url = f'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart/range?vs_currency=usd&from=1627297200&to=1627642800'

In [63]:
response = requests.get(url).json()
print(json.dumps(response, indent=2, sort_keys=True))

{
  "market_caps": [
    [
      1627297318275,
      722607838467.6454
    ],
    [
      1627300803222,
      722028540140.1364
    ],
    [
      1627304514320,
      726300563211.9984
    ],
    [
      1627308025111,
      720583929997.6495
    ],
    [
      1627311741179,
      719023603929.4657
    ],
    [
      1627315278319,
      724985032029.1024
    ],
    [
      1627318859280,
      735071750429.9723
    ],
    [
      1627322579119,
      736644819963.804
    ],
    [
      1627326130343,
      747538939197.5043
    ],
    [
      1627329679842,
      743297629317.7163
    ],
    [
      1627333270433,
      743297629317.7163
    ],
    [
      1627336892558,
      698746226547.2186
    ],
    [
      1627340474993,
      701782668309.3649
    ],
    [
      1627344137670,
      698654120074.028
    ],
    [
      1627347730286,
      701039861923.0902
    ],
    [
      1627351376223,
      694248059560.9375
    ],
    [
      1627354854942,
      688206555089.2941
    ],
    [
      1627358508281,
      690912607017.9905
    ],
    [
      1627362080036,
      697785062261.552
    ],
    [
      1627365779934,
      697297016860.4247
    ],
    [
      1627369266377,
      694089328787.39
    ],
    [
      1627372833041,
      693070859543.7709
    ],
    [
      1627376551488,
      700831960731.0629
    ],
    [
      1627380046957,
      703945978490.7458
    ],
    [
      1627383683906,
      705977660709.0425
    ],
    [
      1627387374383,
      716067968147.4506
    ],
    [
      1627390830402,
      724514721127.2997
    ],
    [
      1627394409817,
      726210832477.8087
    ],
    [
      1627398043144,
      716267727908.99
    ],
    [
      1627401772800,
      715577741754.6956
    ],
    [
      1627405262919,
      710706009625.257
    ],
    [
      1627408890262,
      710083864649.3204
    ],
    [
      1627412429132,
      715347758323.6965
    ],
    [
      1627416061197,
      714269033812.8777
    ],
    [
      1627419784941,
      715024902953.8741
    ],
    [
      1627423267008,
      718229676863.8141
    ],
    [
      1627426876003,
      736957693520.6625
    ],
    [
      1627430459086,
      732311951673.3547
    ],
    [
      1627434031895,
      734301997027.5798
    ],
    [
      1627437686896,
      748113441700.4291
    ],
    [
      1627441210000,
      748557334346.5458
    ],
    [
      1627444940845,
      751807661268.3212
    ],
    [
      1627448402938,
      745532707429.9032
    ],
    [
      1627452053273,
      751993206642.2451
    ],
    [
      1627455695343,
      740025525658.6757
    ],
    [
      1627459274336,
      749389999150.6624
    ],
    [
      1627462925798,
      741324214775.1707
    ],
    [
      1627466425737,
      747602727068.8307
    ],
    [
      1627470163128,
      754374950492.984
    ],
    [
      1627473755723,
      765929793673.24
    ],
    [
      1627477278395,
      744918705244.0948
    ],
    [
      1627480808709,
      741777298066.0647
    ],
    [
      1627484504909,
      743063835819.732
    ],
    [
      1627488039736,
      746493525919.0266
    ],
    [
      1627491628115,
      750638967928.5701
    ],
    [
      1627495305553,
      721823005443.7589
    ],
    [
      1627498801146,
      746357500859.4017
    ],
    [
      1627502467728,
      758306420751.8856
    ],
    [
      1627506123956,
      752312420777.2013
    ],
    [
      1627509734355,
      752246666330.72
    ],
    [
      1627513298279,
      746129214055.7672
    ],
    [
      1627516823553,
      751371299910.5153
    ],
    [
      1627520440235,
      751371299910.5153
    ],
    [
      1627524106872,
      743732120403.7306
    ],
    [
      1627527740674,
      749087430805.6462
    ],
    [
      1627531275339,
      744780000220.1729
    ],
    [
      1627534857660,
      753091988654.5422
    ],
    [
      1627538485294,
      753250709611.0177
    ],
    [
      1627542082115,
      751413876830.9554
    ],
    [
      1627545641250,
      750812473299.8557
    ],
    [
      1627549280800,
      751264397632.5886
    ],
    [
      1627552900128,
      762373070687.3712
    ],
    [
      1627556410434,
      753928866024.069
    ],
    [
      1627560078229,
      744412131141.996
    ],
    [
      1627563780839,
      745899059047.9701
    ],
    [
      1627567325442,
      749158922162.6565
    ],
    [
      1627570945276,
      749341127584.6034
    ],
    [
      1627574401667,
      750789396549.0511
    ],
    [
      1627578093281,
      746415626620.3612
    ],
    [
      1627581668085,
      746575015563.1558
    ],
    [
      1627585221483,
      740578882057.9376
    ],
    [
      1627588911749,
      742269550155.7208
    ],
    [
      1627592433942,
      746661816945.6138
    ],
    [
      1627596060613,
      742654287002.257
    ],
    [
      1627599648897,
      748040028888.0724
    ],
    [
      1627603285544,
      750407963580.4731
    ],
    [
      1627606887543,
      749794782430.8577
    ],
    [
      1627610468550,
      752051621077.9656
    ],
    [
      1627614191784,
      751355448823.5837
    ],
    [
      1627617776038,
      750311420016.8444
    ],
    [
      1627621318680,
      745283593002.1947
    ],
    [
      1627624870544,
      745793372832.1393
    ],
    [
      1627628492443,
      747604599574.8702
    ],
    [
      1627632113572,
      746743293025.8889
    ],
    [
      1627635667664,
      733029858668.4866
    ],
    [
      1627639273293,
      726098528611.7849
    ]
  ],
  "prices": [
    [
      1627297318275,
      38503.96909845663
    ],
    [
      1627300803222,
      38429.726790135705
    ],
    [
      1627304514320,
      38700.54318789168
    ],
    [
      1627308025111,
      38395.845376580975
    ],
    [
      1627311741179,
      38342.041130052734
    ],
    [
      1627315278319,
      38641.072316134705
    ],
    [
      1627318859280,
      39167.47926883704
    ],
    [
      1627322579119,
      39240.53669847888
    ],
    [
      1627326130343,
      39841.37026913555
    ],
    [
      1627329679842,
      39580.47948944336
    ],
    [
      1627333270433,
      37587.10337061645
    ],
    [
      1627336892558,
      37230.71787479864
    ],
    [
      1627340474993,
      37413.73677140341
    ],
    [
      1627344137670,
      37226.65332404864
    ],
    [
      1627347730286,
      37385.81365313333
    ],
    [
      1627351376223,
      36986.68069043319
    ],
    [
      1627354854942,
      36547.97726834441
    ],
    [
      1627358508281,
      36890.35822260365
    ],
    [
      1627362080036,
      37179.89530910283
    ],
    [
      1627365779934,
      37156.29712281256
    ],
    [
      1627369266377,
      36982.80509098118
    ],
    [
      1627372833041,
      36973.08872011078
    ],
    [
      1627376551488,
      37321.58415379447
    ],
    [
      1627380046957,
      37507.766061602175
    ],
    [
      1627383683906,
      37806.59645355601
    ],
    [
      1627387374383,
      38146.7780777746
    ],
    [
      1627390830402,
      38642.00898678301
    ],
    [
      1627394409817,
      38693.71252949519
    ],
    [
      1627398043144,
      38147.613972103834
    ],
    [
      1627401772800,
      38195.58177961262
    ],
    [
      1627405262919,
      37691.22101088084
    ],
    [
      1627408890262,
      37834.076178031064
    ],
    [
      1627412429132,
      38001.26919978973
    ],
    [
      1627416061197,
      38056.914673895844
    ],
    [
      1627419784941,
      38078.87846278329
    ],
    [
      1627423267008,
      38267.710998321556
    ],
    [
      1627426876003,
      39265.54228869781
    ],
    [
      1627430459086,
      39076.59377063225
    ],
    [
      1627434031895,
      39123.753751063196
    ],
    [
      1627437686896,
      39850.20218419877
    ],
    [
      1627441210000,
      39891.519371217604
    ],
    [
      1627444940845,
      39731.45259646625
    ],
    [
      1627448402938,
      39773.54171647967
    ],
    [
      1627452053273,
      40065.83892536083
    ],
    [
      1627455695343,
      39377.92807162509
    ],
    [
      1627459274336,
      39927.007254017924
    ],
    [
      1627462925798,
      39512.86456257924
    ],
    [
      1627466425737,
      39830.67723351484
    ],
    [
      1627470163128,
      40192.36235006664
    ],
    [
      1627473755723,
      40780.77957614079
    ],
    [
      1627477278395,
      39666.4395760909
    ],
    [
      1627480808709,
      39520.79058417729
    ],
    [
      1627484504909,
      39493.698279865406
    ],
    [
      1627488039736,
      39756.4612267934
    ],
    [
      1627491628115,
      39992.72687640625
    ],
    [
      1627495305553,
      38457.39944860085
    ],
    [
      1627498801146,
      40840.142596120655
    ],
    [
      1627502467728,
      40410.51017604738
    ],
    [
      1627506123956,
      40081.570499394125
    ],
    [
      1627509734355,
      40187.29458884765
    ],
    [
      1627513298279,
      39752.00398813865
    ],
    [
      1627516823553,
      40031.19824444798
    ],
    [
      1627520440235,
      39760.47858861325
    ],
    [
      1627524106872,
      39692.152525704005
    ],
    [
      1627527740674,
      39901.779374393984
    ],
    [
      1627531275339,
      39680.283235128205
    ],
    [
      1627534857660,
      40160.85590008955
    ],
    [
      1627538485294,
      40173.839656605036
    ],
    [
      1627542082115,
      40031.82873267897
    ],
    [
      1627545641250,
      40000.824366632034
    ],
    [
      1627549280800,
      40017.77062972872
    ],
    [
      1627552900128,
      40616.613873363596
    ],
    [
      1627556410434,
      40116.34699376695
    ],
    [
      1627560078229,
      39659.51820341666
    ],
    [
      1627563780839,
      39740.83614408671
    ],
    [
      1627567325442,
      39876.15577991498
    ],
    [
      1627570945276,
      39921.797825258
    ],
    [
      1627574401667,
      39945.981398480195
    ],
    [
      1627578093281,
      39765.78033491
    ],
    [
      1627581668085,
      39852.1528877297
    ],
    [
      1627585221483,
      39476.953675657656
    ],
    [
      1627588911749,
      39725.4789623634
    ],
    [
      1627592433942,
      39764.044897266795
    ],
    [
      1627596060613,
      39564.840253704555
    ],
    [
      1627599648897,
      39838.6221249737
    ],
    [
      1627603285544,
      39977.75693922764
    ],
    [
      1627606887543,
      39945.38746787706
    ],
    [
      1627610468550,
      40101.45891910641
    ],
    [
      1627614191784,
      40023.81107477142
    ],
    [
      1627617776038,
      39967.381433383845
    ],
    [
      1627621318680,
      39704.34729299916
    ],
    [
      1627624870544,
      39724.827215039215
    ],
    [
      1627628492443,
      39826.26788181563
    ],
    [
      1627632113572,
      39781.78094875293
    ],
    [
      1627635667664,
      38909.40426718612
    ],
    [
      1627639273293,
      38681.764210954556
    ]
  ],
  "total_volumes": [
    [
      1627297318275,
      39533836623.89689
    ],
    [
      1627300803222,
      39988579383.86375
    ],
    [
      1627304514320,
      40858692330.850174
    ],
    [
      1627308025111,
      41501368434.11426
    ],
    [
      1627311741179,
      41633238069.546814
    ],
    [
      1627315278319,
      42042917329.55637
    ],
    [
      1627318859280,
      43609231396.22439
    ],
    [
      1627322579119,
      44572824593.77232
    ],
    [
      1627326130343,
      46187456911.149155
    ],
    [
      1627329679842,
      48007165673.3384
    ],
    [
      1627333270433,
      49052751005.924805
    ],
    [
      1627336892558,
      51869670450.53119
    ],
    [
      1627340474993,
      53464100036.70941
    ],
    [
      1627344137670,
      53475930015.58891
    ],
    [
      1627347730286,
      52411089918.36721
    ],
    [
      1627351376223,
      45138903841.98485
    ],
    [
      1627354854942,
      43760688347.36959
    ],
    [
      1627358508281,
      44369741336.62781
    ],
    [
      1627362080036,
      44558761430.726166
    ],
    [
      1627365779934,
      44270017264.12354
    ],
    [
      1627369266377,
      43057629287.27826
    ],
    [
      1627372833041,
      42171878797.34668
    ],
    [
      1627376551488,
      41892887870.7584
    ],
    [
      1627380046957,
      42230287387.425964
    ],
    [
      1627383683906,
      42778708184.51314
    ],
    [
      1627387374383,
      43008944008.380455
    ],
    [
      1627390830402,
      43810665235.30334
    ],
    [
      1627394409817,
      43827032782.041695
    ],
    [
      1627398043144,
      44568671063.41708
    ],
    [
      1627401772800,
      45063941895.856224
    ],
    [
      1627405262919,
      43542635853.62557
    ],
    [
      1627408890262,
      43155328418.408844
    ],
    [
      1627412429132,
      42957986119.22938
    ],
    [
      1627416061197,
      41144463287.95519
    ],
    [
      1627419784941,
      37731273480.73275
    ],
    [
      1627423267008,
      35989730465.670944
    ],
    [
      1627426876003,
      36567610689.32963
    ],
    [
      1627430459086,
      36401287454.43055
    ],
    [
      1627434031895,
      36494725148.5793
    ],
    [
      1627437686896,
      37147600927.51561
    ],
    [
      1627441210000,
      38428269954.914604
    ],
    [
      1627444940845,
      38791161503.51245
    ],
    [
      1627448402938,
      38891973029.93078
    ],
    [
      1627452053273,
      39392730457.09353
    ],
    [
      1627455695343,
      39264918032.79081
    ],
    [
      1627459274336,
      40358685077.34535
    ],
    [
      1627462925798,
      40091440222.91119
    ],
    [
      1627466425737,
      40343313779.775764
    ],
    [
      1627470163128,
      40741196550.525856
    ],
    [
      1627473755723,
      41890234715.66109
    ],
    [
      1627477278395,
      41338407761.231895
    ],
    [
      1627480808709,
      41413232630.61153
    ],
    [
      1627484504909,
      40518473397.21392
    ],
    [
      1627488039736,
      40308906629.41434
    ],
    [
      1627491628115,
      39657182209.29165
    ],
    [
      1627495305553,
      39344055700.52038
    ],
    [
      1627498801146,
      42640345161.71155
    ],
    [
      1627502467728,
      42722558854.35323
    ],
    [
      1627506123956,
      43020334928.35042
    ],
    [
      1627509734355,
      43022033367.83059
    ],
    [
      1627513298279,
      42121178542.957085
    ],
    [
      1627516823553,
      41369107422.717026
    ],
    [
      1627520440235,
      40630870087.6323
    ],
    [
      1627524106872,
      40133503167.510796
    ],
    [
      1627527740674,
      38651023642.70863
    ],
    [
      1627531275339,
      37273472880.9672
    ],
    [
      1627534857660,
      37360473855.66718
    ],
    [
      1627538485294,
      37291986138.97101
    ],
    [
      1627542082115,
      36620766860.75234
    ],
    [
      1627545641250,
      36137327917.92469
    ],
    [
      1627549280800,
      35838269161.39884
    ],
    [
      1627552900128,
      36718356727.52863
    ],
    [
      1627556410434,
      35687259430.58094
    ],
    [
      1627560078229,
      34973724802.54037
    ],
    [
      1627563780839,
      34583454593.823975
    ],
    [
      1627567325442,
      33551134757.30926
    ],
    [
      1627570945276,
      33229073270.03653
    ],
    [
      1627574401667,
      33128021433.824642
    ],
    [
      1627578093281,
      32641876268.966816
    ],
    [
      1627581668085,
      31519852098.124043
    ],
    [
      1627585221483,
      30064053258.10843
    ],
    [
      1627588911749,
      28955017502.35809
    ],
    [
      1627592433942,
      28501700512.582302
    ],
    [
      1627596060613,
      28142217558.18452
    ],
    [
      1627599648897,
      28010445757.33099
    ],
    [
      1627603285544,
      28717414113.01727
    ],
    [
      1627606887543,
      28806601741.70324
    ],
    [
      1627610468550,
      28559545192.120857
    ],
    [
      1627614191784,
      28540385494.919064
    ],
    [
      1627617776038,
      28395184297.191563
    ],
    [
      1627621318680,
      28243049834.908543
    ],
    [
      1627624870544,
      27928469101.027977
    ],
    [
      1627628492443,
      27847853325.32641
    ],
    [
      1627632113572,
      27610251735.504673
    ],
    [
      1627635667664,
      27656531718.4548
    ],
    [
      1627639273293,
      29031471904.47569
    ]
  ]
}

In [64]:
prices_df = pd.DataFrame(response['prices'])
prices_df.columns = ['date', 'price']

In [69]:
prices_df['date'] = pd.to_datetime(prices_df['date'], unit='s')
prices_df

                            date         price
0  1970-01-01 00:27:07.297318275  38503.969098
1  1970-01-01 00:27:07.300803222  38429.726790
2  1970-01-01 00:27:07.304514320  38700.543188
3  1970-01-01 00:27:07.308025111  38395.845377
4  1970-01-01 00:27:07.311741179  38342.041130
..                           ...           ...
91 1970-01-01 00:27:07.624870544  39724.827215
92 1970-01-01 00:27:07.628492443  39826.267882
93 1970-01-01 00:27:07.632113572  39781.780949
94 1970-01-01 00:27:07.635667664  38909.404267
95 1970-01-01 00:27:07.639273293  38681.764211

[96 rows x 2 columns]